hyperskill_project:
  id: 370
  ide_files: https://cogniterra.org/media/attachments/lesson/30074/additional_files.json
  is_template_based: false
  use_ide: true
  environment: unittest
update_date: "Thu, 30 May 2024 09:35:06 UTC"
stages:
  - id: 2188
    step: 31342
    is_completed: true
  - id: 2189
    step: 31343
    is_completed: true
  - id: 2190
    step: 31344
    is_completed: true
  - id: 2191
    step: 31345
    is_completed: true
  - id: 2192
    step: 31346
    is_completed: true
  - id: 2193
    step: 31347
    is_completed: true
topics:
  0:
    - title: What is math?
      theory_id: 28537
    - title: Applications of math
      theory_id: 28832
    - title: "Math notations, formulas, and statements"
      theory_id: 28757
    - title: Basic concepts
      theory_id: 26143
    - title: Computer algorithms
      theory_id: 16547
    - title: Basics of sets
      theory_id: 8220
    - title: Basics of functions
      theory_id: 8857
    - title: Probability and Statistics
      theory_id: 11637
    - title: Sample space
      theory_id: 7309
    - title: Events
      theory_id: 7892
    - title: Formal definition of probability
      theory_id: 10538
    - title: Numerical and categorical data
      theory_id: 24686
    - title: Population and sample
      theory_id: 11274
    - title: "Mean, median, and mode"
      theory_id: 11282
    - title: Intro to Machine Learning
      theory_id: 10403
    - title: Typical ML pipeline
      theory_id: 10411
    - title: Introduction to Python
      theory_id: 5204
    - title: Writing first program
      theory_id: 5208
    - title: "PEP 8: Coding style guide"
      theory_id: 5879
    - title: Taking user's input
      theory_id: 5913
    - title: If statement
      theory_id: 5953
    - title: Else statement
      theory_id: 5932
    - title: For loop
      theory_id: 6065
    - title: Comments
      theory_id: 6081
    - title: Importing modules
      theory_id: 6019
    - title: The Jupyter Notebook
      theory_id: 12623
    - title: Google Colab
      theory_id: 12631
    - title: While loop
      theory_id: 5940
    - title: "Loop control: break, continue, pass"
      theory_id: 6302
    - title: Class
      theory_id: 6661
    - title: Methods and attributes
      theory_id: 6981
    - title: Introduction to pandas
      theory_id: 10416
    - title: Series
      theory_id: 10421
    - title: DataFrame
      theory_id: 10933
    - title: Accessing data in a DataFrame
      theory_id: 12998
    - title: .loc & .iloc
      theory_id: 13343
    - title: Summarizing numeric columns
      theory_id: 13359
    - title: Summarizing categorical columns
      theory_id: 13351
    - title: Working with missing values
      theory_id: 14686
    - title: Basic data types
      theory_id: 5852
    - title: Variables
      theory_id: 5859
    - title: Invoking functions
      theory_id: 5891
    - title: Boolean type and operations. True and false
      theory_id: 6025
    - title: Comparisons
      theory_id: 5920
    - title: List
      theory_id: 5979
    - title: Declaring functions
      theory_id: 5900
    - title: "Function, arguments and parameters"
      theory_id: 7248
    - title: Quotes and multi-line strings
      theory_id: 5814
    - title: "Working with strings: basic methods"
      theory_id: 6842
    - title: Escape sequences
      theory_id: 7130
    - title: Splitting strings and joining lists
      theory_id: 6972
    - title: Dictionary
      theory_id: 6481
    - title: Type casting
      theory_id: 6224
    - title: Sep and end arguments of print
      theory_id: 7452
  1:
    - title: Installing packages with pip
      theory_id: 6230
    - title: Virtual Environment
      theory_id: 13923
    - title: PyCharm basics
      theory_id: 6193
    - title: Introduction to scikit-learn
      theory_id: 10430
    - title: Train and test sets
      theory_id: 17181
  2:
    - title: Introduction to regression
      theory_id: 11417
    - title: Introduction to classification
      theory_id: 10942
    - title: Preprocessing categorical features
      theory_id: 30029
    - title: Training a model with scikit-learn
      theory_id: 14678
    - title: Decision Trees
      theory_id: 11426
    - title: Accuracy and confusion matrix
      theory_id: 11245
    - title: Decision tree with scikit-learn
      theory_id: 16405
  5:
    - title: Precision and recall
      theory_id: 17562
    - title: sklearn.metrics.classification_report()
      theory_id: 29339
